"""Harness components surrounding the Agent model."""

from dataclasses import dataclass
from typing import Any, Mapping

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
from langchain_core.tools import BaseTool

from .grounding import GroundingService


@dataclass(frozen=True)
class AgentContext:
    """Trusted request data injected by the server, never generated by the model."""

    user_id: int | None
    conversation_id: int | None
    user_message: str


class ConversationMemory:
    """Build bounded LangChain messages from application-owned chat history."""

    def __init__(self, max_messages: int):
        self.max_messages = max_messages

    def build(self, history: list[Mapping[str, Any]], user_message: str) -> list[BaseMessage]:
        messages: list[BaseMessage] = []
        for item in history:
            role = item.get("role")
            content = item.get("content")
            if not isinstance(content, str) or not content.strip():
                continue
            if role == "user":
                messages.append(HumanMessage(content=content.strip()))
            elif role == "assistant":
                messages.append(AIMessage(content=content.strip()))
        messages = messages[-self.max_messages:] if self.max_messages else []
        messages.append(HumanMessage(content=user_message.strip()))
        return messages


@dataclass(frozen=True)
class AgentHarness:
    """Capabilities and policies wrapped around the reasoning model."""

    system_prompt: str
    tools: tuple[BaseTool, ...]
    memory: ConversationMemory
    grounding: GroundingService
    middleware: tuple[Any, ...] = ()

    def __post_init__(self) -> None:
        names = [tool.name for tool in self.tools]
        if not self.system_prompt.strip():
            raise ValueError("Agent harness 必须提供 system prompt")
        if len(names) != len(set(names)):
            raise ValueError("Agent harness 中的 LangChain 工具名称必须唯一")


@dataclass(frozen=True)
class AgentComponents:
    """The complete application Agent definition: model + harness."""

    model: BaseChatModel
    harness: AgentHarness


__all__ = ["AgentComponents", "AgentContext", "AgentHarness", "ConversationMemory"]
